defaults: &defaults 
  adapter: mysql2
  host: 127.0.0.1
  port: 3306
  username: tessitura 
  database: test
  password: hunter2
  pool: 5
  timeout: 5000

test: &test 
  adapter: mysql2
  host: 127.0.0.1
  port: 3306
  username: tessitura 
  password: hunter2
  pool: 5
  timeout: 5000