development:
  adapter: mysql2
  host: 127.0.0.1
  port: 3306
  username: canto
  password: hunter2
  database: development
  pool: 5
  timeout: 5000

test: &test
  adapter: mysql2
  host: 127.0.0.1
  port: 3306
  username: canto
  password: hunter2
  database: test
  pool: 5
  timeout: 5000

production: 
  adapter: mysql2
  host: 127.0.0.1
  port: 3306
  username: canto
  password: hunter2
  database: production
  pool: 5
  timeout: 5000

cucumber:
  <<: *test